# Generated by Django 4.2.21 on 2025-10-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=100)),
                ('uzmanlik_alani', models.CharField(max_length=100)),
                ('biyografi', models.TextField()),
            ],
        ),
    ]
