# Generated by Django 4.2.21 on 2025-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='doktorlar/'),
        ),
    ]
