# Generated by Django 4.2.21 on 2025-10-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0002_doktor_fotograf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelenMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mesaj', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
