# Generated by Django 4.2.21 on 2025-10-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0003_gelenmesaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandevuTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('istedigi_tarih', models.DateField()),
                ('mesaj', models.TextField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hasta_yonetim.doktor')),
            ],
        ),
    ]
