# Generated by Django 4.2.21 on 2025-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0004_randevutalebi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HastaYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('puan', models.IntegerField(choices=[(1, '★☆☆☆☆ (1 Yıldız)'), (2, '★★☆☆☆ (2 Yıldız)'), (3, '★★★☆☆ (3 Yıldız)'), (4, '★★★★☆ (4 Yıldız)'), (5, '★★★★★ (5 Yıldız)')], default=5)),
                ('yorum', models.TextField()),
                ('yayinda', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
