# Generated by Django 4.2.21 on 2025-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0005_hastayorumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hastayorumu',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='yorum_dosyalari/'),
        ),
        migrations.AlterField(
            model_name='hastayorumu',
            name='yayinda',
            field=models.BooleanField(default=True),
        ),
    ]
